export const JOB_TITLES = Array.from(new Set([
  "Accountant", "Actor", "Actuary", "Aeronautical Engineer", "Architect", "Barrister", "Biomedical Scientist",
  "Building Surveyor", "Business Analyst", "Chemical Engineer", "Civil Engineer", "Clinical Psychologist",
  "Computer Scientist", "Construction Manager", "Dentist", "Dietitian", "Doctor", "Economist",
  "Electrical Engineer", "Environmental Consultant", "Fashion Designer", "Financial Advisor",
  "Forensic Scientist", "Graphic Designer", "Human Resources Manager", "Journalist", "Landscape Architect",
  "Lawyer", "Management Consultant", "Marketing Manager", "Mechanical Engineer", "Midwife",
  "Museum Curator", "Music Therapist", "Nurse", "Occupational Therapist", "Optometrist",
  "Paramedic", "Pharmacist", "Physiotherapist", "Pilot", "Primary School Teacher", "Product Designer",
  "Psychiatrist", "Public Relations Officer", "Quantity Surveyor", "Radiographer", "Research Scientist",
  "Secondary School Teacher", "Social Worker", "Software Engineer", "Solicitor", "Speech and Language Therapist",
  "Statistician", "Surgeon", "Systems Analyst", "Teacher", "Town Planner", "UX Designer", "Veterinary Surgeon",
  "Web Developer", "Zoologist", "Advertising Executive", "Air Traffic Controller", "Animator",
  "Archaeologist", "Biochemist", "Broadcast Journalist", "Cartographer", "Chef", "Chiropractor",
  "Civil Service Administrator", "Copywriter", "Counsellor", "Data Scientist", "Detective",
  "Diplomat", "Ecologist", "Editor", "Event Manager", "Film Director", "Flight Attendant",
  "Game Developer", "Geologist", "Health Visitor", "Historian", "Illustrator", "Investment Banker",
  "IT Consultant", "Laboratory Technician", "Librarian", "Logistics Manager", "Marine Biologist",
  "Microbiologist", "Nutritionist", "Oceanographer", "Osteopath", "Pathologist", "Photographer",
  "Physicist", "Podiatrist", "Politician", "Project Manager", "Psychologist", "Publisher",
  "Radiologist", "Real Estate Agent", "Recruiter", "Retail Manager", "Sales Manager", "Scientist",
  "Social Researcher", "Sociologist", "Sports Coach", "Stockbroker", "Supply Chain Manager",
  "Technical Writer", "Translator", "Travel Agent", "Urban Designer", "Video Editor", "Web Designer"
]));
